### PR TITLE
Rename iterator functions to *_iter

### PR DESCRIPTION
**Pull request by c410-f3r**
Code has some automatic code formatting. Compilation and all tests are OK.

### CODE REVIEW

**Comment by AtheMathmo** [comment]
Thanks! Though this wont get merged for a while. As this contains breaking changes I'll be waiting until we have some other changes ready for a 0.4 release.

**Comment by c410-f3r** [comment]
Can we rename `row_iter` to `rows_iter`?

**Comment by AtheMathmo** [comment]
Personally I slightly prefer `row_iter`. Happy to hear from others - I'd like to stick with whichever most closely follows the rest of the community's naming patterns.

**Comment by tafia** [comment]
I tend to prefer rows_iter ...
Even better now that we are doing a breaking change:
- rename rows in rows_len or height
- use rows for the iterator

**Comment by AtheMathmo** [comment]
@tafia thanks for the comment.

>  rename rows in rows_len or height

You mean the `Matrix` field? If so I much prefer `rows`, but certainly wont shut it down if everyone disagrees.

> use rows for the iterator

I assume you mean the `iter()` function and `IntoIter` implementation? This was [briefly discussed](https://github.com/AtheMathmo/rusty-machine/issues/94) before - though again I'm happy to reopen the discussion. I'm come to be pretty happy with the choice to have the _default_ iterators be over all data. I think it is good to have an explicit row iterator function, and also a default `iter` is expected. We definitely want to be able to iterate over the data - as this is not trivial to do for `MatrixSlice` and I'm not sure what else we would call this function if not `iter`.

**Comment by tafia** [comment]
Sorry I'm not sure I followed.

Here is what I thought:
- `iter` iterates every element of the matrix (per *default*, with row major order) ... We may have this one on Matrix only as there is no incentive over a `FlatMap<Rows>` when memory is not contiguous
- `rows` iterates over the rows (returns a `Rows: Iterator<Item=Row>` and `struct Row { inner: &[T] }`, on `BaseMatrix`
- `columns` over the columns ... Similarly with something more complicated for `Column` item ( probably a `MatrixSlice`) on `BaseMatrix`
- no more `..._iter` functions at all as we always return an iterator or a `MatrixSlice`

I must confess that I haven't followed all the discussions so I may be totally off (whatever you choose is probably fine anyway)

**Pull request closed without merging**
