### PR TITLE
Remove MachineEpsilon trait (#60)

### PR DESCRIPTION
**Pull request by c410-f3r**
I dont have a full knowledge of internal operations but I think that this might work since i wasn't able to compile due to naming clonflicts.

### CODE REVIEW

**Comment by AtheMathmo** [comment]
Thank you for getting this in! I'm not sure why this failed on Travis, it worked locally for me...

What was the issue you had with a naming conflict? Will `cargo update` fix this?

I'll try and hold out to see if Travis will pass this later, but I don't see any issues on my end.

**Comment by tafia** [comment]
Is Travis error linked to this:
https://github.com/travis-ci/travis-ci/issues/6654

**Comment by AtheMathmo** [comment]
Looks like it, thanks @tafia ! 

Fortunately it seems a fix was pushed ~30 minutes ago. I'll try rebuilding now.

**Comment by AtheMathmo** [comment]
I think this is ready to merge now. Can I get confirmation from @Andlon please as he did the original `MachineEpsilon` work?

**Comment by Andlon** [comment]
@AtheMathmo: can't think of anything else that needs changing! Looks good to me.

**Pull request merged**
